name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - shell: bash
      run: |
        ls
    - name: upload docker file
      uses: actions/upload-artifact@v2
      with:
        name: test_docker
        path: .
   
